# Generated by Django 5.1.15 on 2026-06-21 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del curso (ej: Introducción al uso de Smartphones).', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción general dirigida a los adultos mayores.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professor', models.OneToOneField(help_text='Usuario con rol PROFESSOR propietario y administrador de este curso.', on_delete=django.db.models.deletion.CASCADE, related_name='course_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre del bloque (ej: Módulo 1: Perdiendo el miedo a la pantalla).', max_length=255)),
                ('order', models.PositiveIntegerField(default=1, help_text='Orden posicional para renderizar en el frontend.')),
                ('course', models.ForeignKey(help_text='Curso al que pertenece este módulo de aprendizaje.', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la lección (ej: Clase 1: Cómo encender el dispositivo).', max_length=255)),
                ('duration', models.CharField(blank=True, help_text='Duración estimada visible para el alumno (ej: 15 minutos).', max_length=50)),
                ('resource_type', models.CharField(choices=[('PDF', 'Documento de Lectura (PDF)'), ('YTB', 'Video de YouTube')], default='PDF', help_text='Tipo de material de estudio que complementará la IA en el futuro.', max_length=3)),
                ('resource_url', models.URLField(blank=True, help_text='URL directa de YouTube o del archivo PDF guardado.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(help_text='Módulo contenedor de esta clase.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
