# Generated by Django 5.1.15 on 2026-06-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el curso está activo actualmente.'),
        ),
    ]
