# Generated by Django 5.1.15 on 2026-06-27 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.CharField(blank=True, default='general', help_text='Disciplina a la que pertenece.', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Medio'), ('advanced', 'Avanzado')], default='beginner', help_text='Nivel de dificultad.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, default='', help_text='¿Qué logrará el alumno?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción general.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica si el curso está activo.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.OneToOneField(help_text='Usuario con rol PROFESSOR propietario de este curso.', on_delete=django.db.models.deletion.CASCADE, related_name='course_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Título del curso.', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, default='15 minutos', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resource_type',
            field=models.CharField(choices=[('PDF', 'Documento de Lectura (PDF)'), ('YTB', 'Video de YouTube')], default='PDF', max_length=3),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resource_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Título de la lección.', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(help_text='Nombre del bloque.', max_length=255),
        ),
    ]
