# Generated by Django 5.1.15 on 2026-06-29 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_discipline_course_level_course_objectives_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcription',
            field=models.TextField(blank=True, default='', help_text='Transcripción del video o texto completo para lectores de pantalla.'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Porcentaje de respuestas correctas (0.0 a 100.0)')),
                ('passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Texto de la pregunta que fue contestada de forma incorrecta.')),
                ('selected_option', models.CharField(help_text='Opción que seleccionó el estudiante.', max_length=255)),
                ('correct_option', models.CharField(help_text='Opción correcta de la pregunta.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Puntuación dada (1 a 5 estrellas)', null=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Intentos de realización de esta lección o su cuestionario')),
                ('frustration_level', models.IntegerField(default=0, help_text='Nivel de frustración estimado para esta lección (0 a 5)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.FloatField(default=0.0, help_text='Porcentaje de avance general del curso (0.0 a 100.0)')),
                ('global_frustration', models.IntegerField(default=0, help_text='Nivel de frustración general estimado (0 a 5)')),
                ('is_completed', models.BooleanField(default=False, help_text='Indica si el estudiante finalizó el curso.')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el alumno inició el curso.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha en que el alumno completó el curso.', null=True)),
                ('total_time_spent', models.DurationField(blank=True, help_text='Tiempo total empleado para culminar el curso.', null=True)),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Fecha de la última interacción del estudiante con el curso.')),
                ('inactivity_alert_sent', models.BooleanField(default=False, help_text='Evita duplicar alertas de inactividad enviadas.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_states', to='courses.course')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lesson')),
                ('current_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
