# Generated by Django 5.1.15 on 2026-07-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_transcription_quizattempt_wrongquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.TextField(blank=True, default='', help_text='URL o data-URI (base64) de la imagen de portada.'),
        ),
    ]
