# Generated by Django 5.1.15 on 2026-07-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(help_text='Usuario con rol PROFESSOR propietario de este curso.', on_delete=django.db.models.deletion.CASCADE, related_name='courses_managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
