# Generated by Django 5.1.15 on 2026-06-19 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='font_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', help_text='Tamaño de tipografía para accesibilidad.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Activar contraste elevado para accesibilidad.'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.OneToOneField(help_text='Usuario propietario de esta configuración.', on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='voice_guidance',
            field=models.BooleanField(default=False, help_text='Activar guía por voz para accesibilidad.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='URL de la imagen de avatar del usuario.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Número telefónico de contacto.', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STUDENT', 'Alumno'), ('PROFESSOR', 'Profesor')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('primario_completo', 'Primario Completo'), ('primario_incompeto', 'Primario Incompleto'), ('secundario_incompleto', 'Secundario Incompleto'), ('secundario_completo', 'Secundario Completo'), ('terciario_completo', 'Terciario Completo'), ('terciario_en_curso', 'Terciario en Curso'), ('terciario_incompleto', 'Terciario Incompleto'), ('universitario_completo', 'Universitario Completo'), ('universitario_en_curso', 'Universitario en Curso'), ('universitario_incompleto', 'Universtario Incompleto')], max_length=50)),
                ('estado_laboral', models.CharField(blank=True, choices=[('activo', 'Activo'), ('desempleado', 'Desempleado')], max_length=20)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('ND', 'Prefiero no decirlo')], max_length=2)),
                ('objetivo_principal', models.CharField(blank=True, choices=[('empleo', 'Mejorar oportunidades laborales'), ('personal', 'Desarrollo personal'), ('estudios', 'Apoyo para educación formal'), ('hobby', 'Curiosidad o pasatiempo')], max_length=20)),
                ('disponibilidad_tiempo', models.CharField(blank=True, choices=[('baja', 'Menos de 2 horas semanales'), ('media', 'Entre 2 y 5 horas semanales'), ('alta', 'Más de 5 horas semanales')], max_length=10)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', help_text='Zona horaria del usuario para sincronización de notificaciones y eventos.', max_length=50)),
                ('intereses', models.JSONField(blank=True, default=list)),
                ('frecuencia_entradas', models.PositiveIntegerField(default=0)),
                ('racha_actual_dias', models.PositiveIntegerField(default=0)),
                ('racha_maxima_dias', models.PositiveIntegerField(default=0)),
                ('tiempo_acumulado_app_minutos', models.PositiveIntegerField(default=0)),
                ('tiempo_interaccion_mentor_minutos', models.PositiveIntegerField(default=0)),
                ('cantidad_videos_vistos', models.PositiveIntegerField(default=0)),
                ('tiempo_api_youtube_minutos', models.PositiveIntegerField(default=0)),
                ('desafios_completados', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(help_text='Usuario Django vinculado a estas métricas.', on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
