# Generated by Django 5.1.15 on 2026-06-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STUDENT', 'Alumno'), ('PROFESSOR', 'Profesor')], default='STUDENT', help_text='Rol del usuario en la plataforma.', max_length=20),
        ),
    ]
