# Generated by Django 5.1.15 on 2026-06-15 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='font_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', help_text='Tamaño de tipografía para accesibilidad.', max_length=10),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Activar contraste elevado para accesibilidad.'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.OneToOneField(help_text='Usuario propietario de esta configuración.', on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='voice_guidance',
            field=models.BooleanField(default=False, help_text='Activar guía por voz para accesibilidad.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='URL de la imagen de avatar del usuario.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Número telefónico de contacto.', max_length=50),
        ),
    ]
