# Generated by Django 5.1.15 on 2026-06-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userconfig_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='tiempo_acumulado_app_minutos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='tiempo_api_youtube_minutos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='tiempo_interaccion_mentor_minutos',
            field=models.FloatField(default=0),
        ),
    ]
