# Generated by Django 5.1.15 on 2026-06-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_role_alter_userconfig_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STUDENT', 'Alumno'), ('PROFESSOR', 'Profesor')], default='STUDENT', max_length=20),
        ),
    ]
