# Generated by Django 5.1.15 on 2026-07-15 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_alter_lesson_order_alter_module_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('completed', 'Completado')], default='active', help_text='Estado de la inscripción del alumno.', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exactas de la inscripción.')),
                ('course', models.ForeignKey(help_text='Curso en el que se inscribe el estudiante.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(help_text='Estudiante inscrito en el curso.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollment_enrollment',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
